COUNTRY_TO_ISO_MAP = {'IL': 'IL',
                      'CN': 'CN',
                      'HU': 'HU',
                      'US': 'US',
                      'TR': 'TR',
                      'TW': 'TW',
                      'KP': 'KP',
                      'MX': 'MX',
                      'AF': 'AF',
                      'IN': 'IN',
                      'SV': 'SV',
                      'HK': 'HK',
                      'KR': 'KR',
                      'IT': 'IT',
                      'TH': 'TH',
                      'VN': 'VN',
                      'India': 'IN',
                      'Israel': 'IL',
                      'China': 'CN',
                      'Afghanistan': 'AF',
                      'El Salvador': 'SV',
                      'Hong Kong': 'HK'
                      }
ALL_MANUFACTURER_FEATURES = [
    'id',
    'quote_post_id',
    'status',
    'project',
    'agency',
    'bids',
    'chosen_bids',
    'doc_sl',
    'doc_sf',
    'doc_ml',
    'doc_mf',
    'doc_int',
    'chosen_quote',
    'competing_manufacturers',
    'winning_manufacturers',
    'num_candidates',
    'is_bid_chosen',
    'manufacturer_post_id',
    'vendors',
    'street',
    'house',
    'city',
    'zip',
    'country',
    'employees_num',
    'irs',
    'vat',
    'cnc_turning',
    'cnc_turning_min_diameter',
    'cnc_turning_min_length',
    'cnc_turning_max_diameter',
    'cnc_turning_max_length',
    'cnc_turning_machines_num',
    'cnc_turning_notes',
    'cnc_milling',
    'cnc_milling_min_length',
    'cnc_milling_min_width',
    'cnc_milling_min_height',
    'cnc_milling_max_length',
    'cnc_milling_max_width',
    'cnc_milling_max_height',
    'cnc_milling_machines_num',
    'cnc_milling_notes',
    'cnc_turning_milling',
    'cnc_turning_milling_min_diameter',
    'cnc_turning_milling_min_length',
    'cnc_turning_milling_max_diameter',
    'cnc_turning_milling_max_length',
    'cnc_turning_milling_machines_num',
    'cnc_turning_milling_notes',
    'conventional_turning',
    'conventional_turning_min_diameter',
    'conventional_turning_min_length',
    'conventional_turning_max_diameter',
    'conventional_turning_max_length',
    'conventional_turning_machines_num',
    'conventional_turning_notes',
    'conventional_milling',
    'conventional_milling_min_length',
    'conventional_milling_min_width',
    'conventional_milling_min_height',
    'conventional_milling_max_length',
    'conventional_milling_max_width',
    'conventional_milling_max_height',
    'conventional_milling_machines_num',
    'conventional_milling_notes',
    'sheet_metal_laser_cutting',
    'sheet_metal_laser_cutting_min_length',
    'sheet_metal_laser_cutting_min_width',
    'sheet_metal_laser_cutting_min_thickness',
    'sheet_metal_laser_cutting_max_length',
    'sheet_metal_laser_cutting_max_width',
    'sheet_metal_laser_cutting_max_thickness',
    'sheet_metal_laser_cutting_machines_num',
    'sheet_metal_laser_cutting_notes',
    'sheet_metal_press_break',
    'sheet_metal_press_break_min_length',
    'sheet_metal_press_break_min_width',
    'sheet_metal_press_break_min_thickness',
    'sheet_metal_press_break_max_length',
    'sheet_metal_press_break_max_width',
    'sheet_metal_press_break_max_thickness',
    'sheet_metal_press_break_machines_num',
    'sheet_metal_press_break_notes',
    'sheet_metal_punching',
    'sheet_metal_punching_min_length',
    'sheet_metal_punching_min_width',
    'sheet_metal_punching_min_thickness',
    'sheet_metal_punching_max_length',
    'sheet_metal_punching_max_width',
    'sheet_metal_punching_max_thickness',
    'sheet_metal_punching_machines_num',
    'sheet_metal_punching_notes',
    'sheet_metal_inserts',
    'sheet_metal_weldings',
    'batch_size_10',
    'batch_size_100',
    'batch_size_1000',
    'batch_size_9999',
    'preffered_type_part_manufacturing',
    'preffered_type_assemblies',
    'preffered_type_full_turnkey',
    'inspection_formal_inspection',
    'inspection_cmm_inspection',
    'inspection_first_article',
    'disabled_group_stainless_steel',
    'disabled_group_aluminum_alloy',
    'disabled_group_carbon_alloy_steel',
    'disabled_group_nickel_alloy',
    'disabled_group_titanium_alloy',
    'disabled_group_cooper_alloy',
    'disabled_group_plastics',
    'certifications',
    'qa_lab_capability_desc',
    'traceability_system',
    'sqe_team_and_supplier_quality_policy',
    'quality_system_desc',
    'company_id',
    'currency',
    'international',
    'shipping_cost',
    'participation_count'
]
ALL_PROJECT_FEATURES = [
    'post_id',
    'status',
    'approval_date',
    'delivery_date',
    'agency',
    'engineer',
    'manufacturer',
    'vendor',
    'description',
    'parts',
    'plan',
    'time_to_bid',
    'time_to_quote',
    'time_to_production',
    'one_manufacturer',
    'use_avl',
    'req_certifications',
    'certifications',
    'req_turning',
    'req_milling',
    'req_sheet_metal',
    'req_sheet_metal_inserts',
    'req_materials',
    'req_inspections',
    'req_batches',
    'excluded_manufacturers',
    'bids_manufacturers',
    'time_to_po',
    'quote',
    'manufacturers',
    'name',
    'use_certifications',
    'winning_bids',
    'sent_to_mf',
    'sent_to_engineer',
    'avls',
    'notif_quote',
    'draft_manufacturers',
    'delivery_date_int',
    'delivered_on',
    'is_iai',
    'note',
    'time_to_quote_ext',
    'times_updated',
    'local_vendors',
    'global_vendors',
    'excluded_manufacturers_admin',
    'project_creation_date',
    'approval_date_Ymd',
    'num_days_from_creation_to_approval',
    'project_creation_date_year',
    'project_creation_date_month',
    'project_creation_date_day',
    'approval_date_year',
    'approval_date_month',
    'approval_date_day',
    'project_creation_year_month',
    'project_creation_date_Ym',
    'is_quote_carried_out'
]

PRICE_BUCKETS = [1, 1.5, 2.5, 4, 6, 10, 15, 20, 30, 50, 65, 80, 100, 125, 150, 200, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000]
MYSQL_PW = 'mysql123'
MYSQL_ROOT = 'root'
MYSQL_MANUFUTURE_DB = 'manufuture'
MYSQL_HOST = 'localhost'

WERK_START_DIR = "/Users/ofriedler/Data/manufuture_data/werk_data/"
PROJECT_DIR_PATH = '/Users/ofriedler/Dropbox/Work/Consultation/Manufuture/dev/manufuture/'
STATIC_DATA_DIR_PATH = PROJECT_DIR_PATH + '/manu_python/static_data/'
MIN_NUM_BIDS_PER_MANUFACTURER = 4
MANUFACTURER_BID_LABEL_COLUMN_NAME = 'is_manuf_bid'
PART_NETSUITE_MEAN_PRICE_COLUMN_NAME = 'Rate mean_netsuite'

COLUMNS_DTYPES = {'house': str, 'cnc_turning_notes': str, 'zip': str, 'cnc_milling_notes': str
    , 'cnc_turning_milling_notes': str, 'conventional_turning_notes': str, 'conventional_milling_notes': str
    , 'sheet_metal_laser_cutting_notes': str, 'sheet_metal_press_break_notes': str, 'sheet_metal_punching_notes': str
    , 'qa_lab_capability_desc': str, 'traceability_system': str, 'sqe_team_and_supplier_quality_policy': str
    , 'quality_system_desc': str, 'company_id':str, 'state':str, 'manufacture_state':str
}